#!/usr/bin/python3
import sys

def factorize(n):
    """
    Returns a list of factor pairs for the given integer n.
    """
    factors = []
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            factors.append((i, n//i))
    return factors

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

filename = sys.argv[1]
with open(filename) as f:
    for line in f:
        n = int(line.strip())
        factor_pairs = factorize(n)
        for p, q in factor_pairs:
            print(f"{n}={p}*{q}")
